### ISSUE TITLE
Code injected when AdBlockUltimate activated

### ISSUE THREAD

**Issue by svatas** [adblockultimate/AdBlockUltimate-firefox#9] opened 2017-12-27 09:58 UTC
Dear all,

I found strange behaviour when AdBlockUltimate for Firefox activated. I just discovered presentation framework impress.js. When you open the presentation and try to save it, it is done with the help of CTRL+S. Then the page is asved in HTML file. Standard behaviour as expected. However I was curious why the length of the file is so huge. Pretty small presentation and the code was some 410 Kb!

I went into the code of page a found strange elements inside the code (just short example)  :
`<style type="text/css">embed[height="175"][width="175"], embed[height="200"][width="100%"], embed[height="200"][width="175"], embed[height="233"][width="280"], embed[height="250"][width="175"], embed[width="100%"][height="100"], embed[width="1000"][height="150"], embed[width="120"][height="240"], embed[width="120"][height="600"], embed[width="160"][height="600"], embed[width="180"][height="300"], embed[width="180"][height="530"], embed[width="200"][height="230"], embed[width="200"][height="250"], embed[width="200"][height="300"], embed[width="200"][height="400"], embed[width="200"][height="500"], embed[width="210"][height="270"], embed[width="212"][height="300"], embed[width="215"][height="359"], ....`

I was doing some analysis WHAT is causing this and found, when the Adblocker is deactivated, no additional code is injected into the file. The same file (presentation) saved with deactvated Adblocker produce file which is smaller (some 8 Kb!)

If you compare both files, you can see that some small minor changes in name of file inserted into code and the main difference is that "strange" part after `<style` type="text/css">embed`

The only difference is if AdBlocker is activated/deactivated. When I tried different Adblock add-on, no injection found.

Can you investigate? Is it done by the "hacked" version of AdBlockerUltimate on my computer or in your repository? is it by purpose? Can anybody else reproduce this?

How to reproduce?
- Activate AdBlockerUtlimate (version from 12.12.2017)
- Go to the http://impress.github.io/impress.js/#/bored
- Press CTRL-S and save the file. The length of the file will be some 361 Kb
- Deactivate AdBlockerUltimate and restart Firefox
- Go to the http://impress.github.io/impress.js/#/bored
- Press CTRL-S and save the file. The length of the file will be some 26 Kb

In attachment you can find both HTML files for reference. This is pretty strange and needs some explanation. 

As a workaround I deactivated AdBlockerUltimate and switched to different product. And there is no sign about behaviour like this.

[AdBlockerIssue-files.zip](https://github.com/adblockultimate/AdBlockUltimate-firefox/files/1588768/AdBlockerIssue-files.zip)

**Comment by svatas** [comment] 2017-12-27 10:54
Oh well, definitelly I found this : 

https://forums.malwarebytes.com/topic/214257-adblocker-ultimate-inject-coinhive-miner-script-into-browser/

Now it is clear....

Bye, bye...

**Comment by adblockultimate** [comment] 2018-01-03 12:32
Regarding the **first** issue: 
I can see what the problem is. By default our adblocker adds predefined CSS classes that disables elements having IDs that are obviously containing ads. For example if you have <div id="ads-728x90">some content</div> this will be hidden.

What you are seeing here is the CSS that defines which IDs or classes should be hidden to prevent ads. It is weird that this CSS got added to your editor (my guess is that the extension thinks it is a web page - not editor). I'd recommend you turn off the adblocker for this website.

Thanks for the valuable feedback, we will think of a way to fix this.

Regarding **second** issue:
I can see that the MalwareBytes admin closed the thread saying that this is a false positive. Meaning that their software mistakenly marked it as having coinhive miner. What it actually must have detected is our anti-coinhive script - we prevent mining on your PC initiated from web pages.

**Closed by adblockultimate** 2018-01-03 12:32 UTC
